spring.application.name=DigitalAuction

spring.datasource.url=jdbc:mysql://localhost:3306/auctiondb
spring.datasource.username=auctionadmin
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true